flat_data_viz_cve.Rmd:
  path: dev/flat_data_viz_cve.Rmd
  state: active
  R: R/filter_data.R
  tests: []
  vignettes: vignettes/data-viz.Rmd
  inflate:
    flat_file: dev/flat_data_viz_cve.Rmd
    vignette_name: Data-viz
    open_vignette: true
    check: true
    document: true
    overwrite: ask
