---
title: "flat_cves-harvesting.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# cves_harvesting

```{r function-cves_harvesting}
#' Download CSV from a URL
#'
#' This function downloads a CSV file from a given URL and stores it into a local file.
#' 
#' @param url The URL of the CSV file. Default is "https://cve.mitre.org/data/downloads/allitems.csv".
#' @param file_name The name of the file where the CSV content will be stored. Default is "allitems.csv".
#' @importFrom utils download.file
#' @return A boolean indicating if the file was successfully downloaded.
#' 
#' @examples
#' cves_harvesting()
#' cves_harvesting("https://cve.mitre.org/data/downloads/allitems.csv", "allitems.csv")
#' 
#' @export
cves_harvesting <- function(url = "https://cve.mitre.org/data/downloads/allitems.csv", 
                            file_name = "allitems.csv") {
  # Download the file
  download_status <- tryCatch({
    download.file(url, file_name, mode = "wb")
    TRUE
  }, error = function(e) {
    warning("Error in downloading the file: ", e)
    FALSE
  })
  
  return(download_status)
}

```

```{r examples-cves_harvesting}
cves_harvesting()
```

The following function is to create the test file that will live inside the test folder, as well as the github repository :

```{r}
write_head_to_csv <- function(input_file_name, output_file_name, num_rows = 6) {
  data <- read.csv(input_file_name)
  short_data <- head(data, n = num_rows)
  write.csv(short_data, output_file_name, row.names = FALSE)
}

```

```{r}
#write_head_to_csv(input_file_name = "allitems.csv", output_file_name = "tests/testthat/allitems_test.csv", num_rows = 60)
```


```{r tests-cves_harvesting, warning=FALSE}
test_that("cves_harvesting returns FALSE when an invalid URL is given", {
    expect_false(cves_harvesting("http://this-is-an-invalid-url.csv"))
})

test_that("cves_harvesting returns FALSE when an invalid URL is given", {
    expect_true(cves_harvesting("https://github.com/Cdk29/cveR/blob/main/tests/testthat/allitems_test.csv"))
})
```



```{r}
#' Read Data from CVEs CSV File
#'
#' This function reads a CSV file, skipping the first few rows to retrieve the headers and data separately.
#' It then assigns the header names to the data and returns a dataframe.
#'
#' @param file_name The name of the file to read.
#' 
#' @return A dataframe with data from the CSV file.
#0' 
#' @examples
#' read_data_CVEs("allitems.csv")
#'
#' @export
read_data_CVEs <- function(file_name) {
  headers = read.csv(file_name, skip = 2, nrows = 1, header = TRUE)
  data <- read.csv(file_name, encoding = "ISO-8859-1", skip = 10, header = TRUE, stringsAsFactors = FALSE)
  colnames(data) <- colnames(headers)
  return(data)
}
```

```{r}
#read_data_CVEs("allitems.csv")
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_cves-harvesting.Rmd", vignette_name = "Go further")
```

