# WARNING - Generated by {fusen} from /dev/flat_cves-harvesting.Rmd: do not edit by hand

# test_that("cves_harvesting works", {
# 
# })

test_that("cves_harvesting returns FALSE when an invalid URL is given", {
    expect_false(cves_harvesting("http://this-is-an-invalid-url.csv"))
})
