# WARNING - Generated by {fusen} from /dev/flat_cves-harvesting.Rmd: do not edit by hand

#' Download CSV from a URL
#'
#' This function downloads a CSV file from a given URL and stores it into a local file.
#' 
#' @param url The URL of the CSV file. Default is "https://cve.mitre.org/data/downloads/allitems.csv".
#' @param file_name The name of the file where the CSV content will be stored. Default is "allitems.csv".
#' @importFrom utils download.file
#' @return A boolean indicating if the file was successfully downloaded.
#' 
#' @examples
#' cves_harvesting()
#' cves_harvesting("https://cve.mitre.org/data/downloads/allitems.csv", "allitems.csv")
#' 
#' cves_harvesting()
#' @export
cves_harvesting <- function(url = "https://cve.mitre.org/data/downloads/allitems.csv", 
                            file_name = "allitems.csv") {
  # Download the file
  download_status <- tryCatch({
    download.file(url, file_name, mode = "wb")
    TRUE
  }, error = function(e) {
    warning("Error in downloading the file: ", e)
    FALSE
  })
  
  return(download_status)
}

