# WARNING - Generated by {fusen} from dev/flat_data_viz_cve.Rmd: do not edit by hand

#' @title BTM Topic Modeling with Cooccurrence
#' @description This function applies the Biterm Topic Model (BTM) to a given annotated dataframe,
#' using cooccurrence of terms to build the model.
#' @param df Annotated dataframe containing the text data.
#' @param k Number of topics.
#' @param iter Number of iterations for the Gibbs sampling algorithm.
#' @return A BTM model.
#' @examples
#' data <- data.frame(doc_id = c(1,2,3), xpos = c("NN", "VB", "NN"), token = c("token1", "token2", "token3"))
#' model <- btm_topic_model_cooccurrence(data, k = 5, iter = 1000)
#' library(stopwords)
#' # Read data from CSV
#' df <- read.csv("filtered_data_18_2023.csv")
#' df <- tail(df, 600)
#' df$Description <- iconv(df$Description, from = "ISO-8859-1", to = "UTF-8")
#' # Load the udpipe model
#' ud_model <- udpipe_load_model("english-ewt-ud-2.5-191206.udpipe")
#'
#' # Annotate the text data
#' u_df <- text_annotation(df, "Description", ud_model)
#' # Run Biterm Topic Model with cooccurrence
#' btm_model_cooccurrence <- btm_topic_model_cooccurrence(u_df, k = 10)
#'
#' # Plot the topic model
#' plot(btm_model_cooccurrence)
#'
#'
#' @export
btm_topic_model_cooccurrence <- function(df, k = 10, iter = 2000) {

  # Extract cooccurrences of nouns, adjectives, and verbs within 3 words distance
  biterms <- as.data.table(df)
  biterms <- biterms[, cooccurrence(x = token,
                                    relevant = upos %in% c("PROPN", "ADJ", "VERB")  & 
                                               nchar(token) > 2 & !token %in% stopwords("en"),
                                    skipgram = 5),
                     by = list(doc_id)]
  
  # Build the biterm topic model
  # xpos %in% c("NN", "NNP", "NNS", "VB", "VBD", "VBG", "VBN", "VBP", "VBZ")
  traindata <- subset(df, upos %in% c("PROPN", "ADJ", "VERB")  & !token %in% stopwords("en") & nchar(token) > 2)
  traindata <- traindata[, c("doc_id", "token")]
  model <- BTM(traindata, biterms = biterms, k = k, iter = iter, background = TRUE)
  
  return(model)
}


#' @noRd
filter_data <- function(df) {
  data <- df %>%
    filter(str_detect(Name, "CVE-2023")) %>%
    filter(!str_detect(Description, "This candidate has been reserved"))
  return(data)
}


#' @title Text Annotation
#' @description This function applies the udpipe model to a given dataframe and a specified text column for POS tagging.
#' @param df Dataframe containing the text data.
#' @param text_col Name of the column in df that contains the text data.
#' @param ud_model The udpipe model to use for POS tagging.
#' @return A data frame with annotations from the udpipe model.
#' @examples
#' data <- data.frame(description = c("text1", "text2", "text3"))
#' ud_model <- udpipe_load_model("english-ud-2.0-170801.udpipe")
#' annotated_data <- text_annotation(data, "description", ud_model)
#' u_df <- text_annotation(test_df, "Description", ud_model)
#' head(u_df)
#' @export
text_annotation <- function(df, text_col, ud_model) {
  # Apply the udpipe model to the text data
  ud_data <- udpipe_annotate(ud_model, x = df[[text_col]], tagger = "default", parser = "none")
  ud_data <- as.data.frame(ud_data)
  
  return(ud_data)
}
