# WARNING - Generated by {fusen} from dev/flat_data_viz_cve.Rmd: do not edit by hand

#' Filter Data
#'
#' Filters a data frame based on specific conditions.
#'
#' @param df A data frame.
#' @return A filtered data frame.
#' @import dplyr
#' @importFrom stringr str_detect
#' @export
filter_data <- function(df) {
  data <- df %>%
    dplyr::filter(stringr::str_detect(Name, "CVE-2023")) %>%
    dplyr::filter(!stringr::str_detect(Description, "This candidate has been reserved"))
  return(data)
}

#' @title Text Annotation
#' @description This function applies the udpipe model to a given dataframe and a specified text column for POS tagging.
#' @param df Dataframe containing the text data.
#' @param text_col Name of the column in df that contains the text data.
#' @param ud_model The udpipe model to use for POS tagging.
#' @return A data frame with annotations from the udpipe model.
#' @examples
#' data <- data.frame(description = c("text1", "text2", "text3"))
#' ud_model <- udpipe_load_model("english-ud-2.0-170801.udpipe")
#' annotated_data <- text_annotation(data, "description", ud_model)
#' u_df <- text_annotation(test_df, "Description", ud_model)
#' head(u_df)
#' @export
text_annotation <- function(df, text_col, ud_model) {
  # Apply the udpipe model to the text data
  ud_data <- udpipe_annotate(ud_model, x = df[[text_col]], tagger = "default", parser = "none")
  ud_data <- as.data.frame(ud_data)
  
  return(ud_data)
}

#' @title Update the CVE dataframe
#'
#' @description Add the CVEs present in new_cves dataframe that are not yet present in archived_cve dataframe.
#' The new CVEs are added with the Project as 'new_cves' and Archived status as 'No'.
#'
#' @param new_cves Dataframe The dataframe with new CVEs.
#' @param archived_cve Dataframe The dataframe with archived CVEs.
#'
#' @return Dataframe The updated archived_cve dataframe with new CVEs added.
#' @export
#'
#' @examples
#' updated_cve <- update_cve(new_cves, archived_cve)

#' library(dplyr)
#' library(tidyverse)
#' archived_cve <- update_cve(new_cves, archived_cve)
update_cve <- function(new_cves, archived_cve) {
  # Import necessary libraries
  
  # Find rows in new_cves not present in archived_cve
  new_entries <- anti_join(new_cves, archived_cve, by = "Name")

  # Select necessary columns and fill them with appropriate values
  new_entries <- new_entries %>%
    select(Name) %>%
    mutate(Project = "new_cves", Archived = "No")

  # Append new_entries to archived_cve
  updated_cve <- bind_rows(archived_cve, new_entries)
  
  return(updated_cve)
}

